@startuml активности
skinparam conditionStyle InsideDiamond
|#pink|Студент|
start
:Запрос страницы; 
if (нужна авторизация?) is (нет) then
else (Да)
|#lightblue|Веб-сервер|
label auth1;
#lightblue :**Запрос логина и пароля**;
:Отправить запрос в бд учетных записей;
    |#LightGoldenRodYellow|БД|
    if (логин есть в БД?) is (да) then
        if (пароль соответсвует логину?) is (да) then
        :Отправить подтверждение авторизации;
        else
        :Вернуть ошибку - неправильный пароль;
        endif
    else (нет) 
    : Вернуть ошибку неверный логин;

endif
|#lightblue|Веб-сервер|
if (Авторизация успешна) is (да) then
else (нет)
:Ошибка 401;
stop
endif
endif
|#lightblue|Веб-сервер|
:**Генерация данных**;
:Передача данных;
:Рендер страницы;
|#pink|Студент|
:Просмотр страницы;
stop
@enduml
