@startuml pr2
left to right direction
actor/ Студент as st
actor/ "Сотрудник института" as pr
rectangle ИС_деканата {
  pr -- (запрос оценок студента)
  pr -- (перевести на другой курс)
  pr -- (отчислить студента)
  (запрос к ИС) <|- (перевести на другой курс)
  (запрос к ИС) <|- (отчислить студента)
  (запрос к ИС) <|- (запрос оценок студента)
  st -right-- (запрос расписания)
  st -- (запрос своих оценок)
  (запрос к ИС) <|- (запрос расписания) 
  (запрос к ИС)<|- (запрос своих оценок) 
  (запрос к ИС) -down.> (проверка авторизации) : <<include>>
  (Анализ ввода для статистики) .> (запрос к ИС) : <<extend>>
}

@enduml