@startuml зк2_2
class "Информационная система" {
    {method} - Запрос на сервер обработчик
    {method} + Взаимодействие с запросами
}

class "Сервер обработчик" {
    {field} предзагруженный контент : BLOB
    {method} - Запрос на сервер баз данных 
    {method} # Фронтенд обработчик
    {method} # Бекенд обработчик
}
class "Сервер баз данных"{
    cookie пользователей []
    {method} # Удалить базу
    {method} - Выполнить SQL запрос
    {method} - Сделать бекап
    {method} # Развернуть бекап

}
class Студент  {
    {field} cookie
    {method} + узнать оценки
    {method} + посмотреть расписание
}

"Информационная система" *-- "Сервер обработчик"
"Сервер обработчик" <.. "Сервер баз данных"
Студент --"отправляет \n запросы \n к"  "Информационная система"

@enduml