@startuml posled
participant Client as C
participant Server as S 
==Установка TCP соединения==
C-> S: Запрос соединения  SYN
S --> C: Подготовка соединения успешна, SYN, ACK
note left: Состояние ESTABLISHED
C --> S: ACK
note right: Состояние ESTABLISHED
==SSH обмен идентификационными данными==
C ->S: Обмен версиями протокола, \n и другими вспомогательными данными
S -->C: Обмен версиями протокола, \n и другими вспомогательными данными
|||
==Обмен ключами==
C ->S: Обмен алгоритмами шифрования, обмена ключами, сжатия 
S -->C: Обмен алгоритмами шифрования, обмена ключами, сжатия
hnote across:Происходит выбор приоритетного алгоритма (по предпочтительному порядку)
note left:Генерирует открытый и закрытый ключи.
C-> S: Отправляет свой ключ 
note right: При получении генерирует собственную пару ключей. Генерирует секрет K.\nЗатем генерирует хэш обмена H,\n и подписывает его, генерируя подписанный хэш HS"
S -->C: Отправка сообщения  применив  открытый ключа сервера B, открытый ключ хоста сервера HPub и подпись на хэше обмена HS
note left:Вычисление секрета K и хэша обмена H, проверка подпись хэша обмена HS.
==Генерация новых ключей==
hnote across:Векторы инициализации (IV) обычно представляют собой случайные числа,\n используемые в качестве входных данных для симметричного шифра.\n Их цель состоит в том, чтобы гарантировать, что одно и то же сообщение, зашифрованное дважды, не приведёт к одному и тому же шифротексту.
C ->S: Начальный вектор IV от клиента к серверу: HASH(K || H || «A» || session_id)
note right: Здесь «A» означает одиночный символ A, ASCII 65; \n || символ конкатенации
S -->C: Начальный вектор IV от сервера к клиенту: HASH(K || H || «B» || session_id)
C ->S: Ключ шифрования от клиента к серверу: HASH(K || H || «C» || session_id)
S -->C: Ключ шифрования от сервера к клиенту: HASH(K || H || «D» || session_id)
C ->S: Ключ контроля целостности от клиента к серверу: HASH(K || H || «E» || session_id)
S -->C: Ключ контроля целостности от сервера к клиенту: HASH(K || H || «F» || session_id)
|||
C-->S: Обмен ключами завершён, а все будущие коммуникации должны происходить с использованием новых ключей, созданных выше
S -->C: Обмен ключами завершён, а все будущие коммуникации должны происходить с использованием новых ключей, созданных выше
||| 
hnote across:На этом этапе обе стороны согласовали криптографические примитивы, обменялись секретами и сгенерировали материал ключей для выбранных примитивов.\n Теперь между клиентом и сервером может быть установлен безопасный канал, который обеспечит конфиденциальность и целостность.
@enduml